### ISSUE TITLE
Multi-attack moves breaking the Faint Listener

### ISSUE THREAD

**Issue by TheKnightKarim** [xPXpanD/PixelmonBroadcasts#2]
When the faint listener is being called, on the event.pokemon.hasOwner(); it appears that something is nulling out when (in my case) Bide was used on the pokemon. Just wanted to post here as I was asked by XpanD. 

Possible fix:
Check if the pokemon is null? Weird bug indeed

https://hastebin.com/izacowixen.md

**Comment by xPXpanD** [comment]
There should now be a workaround for this in the upcoming build, 0.4.2! This is related to a Pixelmon bug, so a null check and a log error is the best I can do for now.
