### ISSUE TITLE
Dying resets your toggles

### ISSUE THREAD

**Issue by zPr3d** [xPXpanD/PixelmonBroadcasts#3]
**Describe the bug**
When you set your toggles via /pbroadcasts toggle they are honored up until you die, then they all activate again.

**To Reproduce**
1. Set toggles
2. Die

**Expected behavior**
Toggles to remain, even after death.

**Versions**
 - Pixelmon Broadcasts version: 0.4.2
 - Pixelmon version: Reforged 8.1.2
 - Forge version: 2854
 - SpongeForge version: 2838

**Comment by xPXpanD** [comment]
Thanks for putting this up here. I'll have a look when I next update the sidemod, possibly when the next Pixelmon version comes out. (depending on whether anything breaks)

**Comment by xPXpanD** [comment]
This should now be fixed for the upcoming build! Hoping to have it on the site tomorrow.

EDIT: Might be a bit longer, going for a 0.5 after seeing ElectronicManuel's fork for different boss levels. Another day or two?

**Comment by xPXpanD** [comment]
0.5 is now out!

**Comment by zPr3d** [comment]
Glad to hear! We'll get it on to our server for the next reboot, thanks!
