### ISSUE TITLE
Wrong announcing types of Legends

### ISSUE THREAD

**Issue by zespy12** [xPXpanD/PixelmonBroadcasts#4]
**Describe the bug**
It announce Latios legend spawn as a Mega Legend

**To Reproduce**
1. Get a Latios to spawn
2. Result in chat

**Expected behavior**
When a Latios spawn instead of it annoucing it as a Legend Latios has spawned , it announced as A Legend Mega Latios has spawned

**Screenshots**
Listed below
![unknown](https://user-images.githubusercontent.com/75636647/107164102-0e64a600-69e0-11eb-9e4d-155473fc2ddb.png)

**Versions**
 - Pixelmon Broadcasts version: 0.5
 -  - Pixelmon version: 8.1.2
 - Forge version: 2854
 - Plugin platform name/version: pongeForge 7.3.0

**Additional context**
Nope

**Comment by xPXpanD** [comment]
I see the issue, will have a look for the proper 0.6 release. (or the next test release if we end up needing one)

Thanks!

**Comment by xPXpanD** [comment]
Fixed in 0.6 test 2! Closing.
