### ISSUE TITLE
Alert player on Legend Spawn Event

### ISSUE THREAD

**Issue by zPr3d** [xPXpanD/PixelmonBroadcasts#5]
**Is your feature request related to a problem? Please describe.**
About half of the time a legend spawns, a player doesn't realize it's on them and continues traveling, resulting in a legend despawning.

**Describe the solution you'd like**
The ability to add a player variable to the legend spawn broadcast

**Comment by xPXpanD** [comment]
I'll have a look at this for the next release, sounds like an useful addition if it can be made to work reliably. Thanks!

**Comment by xPXpanD** [comment]
This is now implemented for the upcoming release, to be released when 8.2.0 comes out. Closing!
