### ISSUE TITLE
0.6 - permission checks don't work in ForgeEssentials

### ISSUE THREAD

**Issue by xPXpanD** [xPXpanD/PixelmonBroadcasts#6]
Putting this up for looking into later.

**Comment by unleavenedbread** [comment]
I am experience the same issue. Only OPs can see messages on a server using ForgeEssentials permission modules.

**Comment by xPXpanD** [comment]
Closing this issue (and the project in general) due to me recently having been booted off of the Pixelmon mod team over a minor disagreement, if you can even call it that. Guess that's what 5.5 years on the team gets you... The code's still public and the license is permissive if people want to keep working on it, but I am unable to continue working on these projects myself. Sorry for the bad news.
