### ISSUE TITLE
Shiny and Ultra Beasts notifications not working on server

### ISSUE THREAD

**Issue by KoalaMistico** [xPXpanD/PixelmonBroadcasts#7]
The shiny and ultra beasts spawn notifications don't work. I've tried reintaliing the mod and deleting the config files but nothing seems to work. It was working fine until now and I haven't made any changes to the server. The log notifications for these pokémon doesn't seem to work either.

 - Pixelmon Broadcasts version: 0.6
 - Pixelmon version: Reforged 8.1.2
 - Forge version: 14.23.5.2854
 - Plugin platform: SpongeForge 7.3.0

I'm using LuckPerms for the permissions btw.

**Comment by xPXpanD** [comment]
Thanks for the report.

Can you attach your three Broadcasts config files? The settings file in particular may offer some clues as to what's happening here. Also, do the toggles show up under "/pbroadcasts toggle"? A copy of the server's "latest.log" log after a clean boot may also help.

**Comment by KoalaMistico** [comment]
Here are the files. I must say that all of the sudden the notifications started working again. I didn't do anything and apparently it fixed itself.
[latest (1).log](https://github.com/xPXpanD/PixelmonBroadcasts/files/6337329/latest.1.log)

Sorry but i can't upload the settings file. However it is the default, i haven't touched anything in the file.

**Comment by xPXpanD** [comment]
Did you refresh (remove and restart/reload) the Pixelmon config before, by any chance? The log looks healthy as far as Broadcasts is concerned. (though there's a lot of other messiness there, stuff like Optifine should probably be removed as it's client-only)

**Comment by KoalaMistico** [comment]
nop, i only removed it now that the mod failed.

**Comment by xPXpanD** [comment]
Very strange. If this happens to come up again, please let us know! (and attach a new log from the session with the issue + the three Broadcasts configs that were in use at that point)

**Comment by xPXpanD** [comment]
Closing this due to its age, and the imminent release of 0.6.1. If this does come up again, please open a new topic with the configs attached as well.
