### ISSUE TITLE
Custom chat alert

### ISSUE THREAD

**Issue by MircoCagni** [xPXpanD/PixelmonBroadcasts#8]
What if i want chat alert for a list of uncommon pokemon like Dragonite, is this possible in some way? just asking

**Comment by xPXpanD** [comment]
This is not currently possible, though I'd like to implement some sort of custom list option in the (distant?) future. Other features have priority for now, but keep an eye on the changelogs to see what happens when!

**Comment by MircoCagni** [comment]
Understandable have a nice day 👍 :)
